# Generated by Django 5.2.5 on 2025-12-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='topic_title',
        ),
        migrations.AddField(
            model_name='tip',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='pages.topic'),
        ),
    ]
